<a href="https://colab.research.google.com/github/Hallymhwangbo/2020-AI_minseo/blob/master/00_2_python_1_4_1~1_5_6.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

1.4.1 파일로 저장하기

In [1]:
%cd/content/drive/My Drive/2020 1학년 1학기/인공지능개론/python/hungry.ipynb #해결하지못한부분


[Errno 2] No such file or directory: '/content/drive/My Drive/2020 1학년 1학기/인공지능개론/python/hungry.ipynb #해결하지못한부분'
/content


In [2]:
python hungry.ipynb #해결하지못한부분

SyntaxError: ignored

1.4.2 클래스

In [3]:
class Man:
  def __init__(self, name):
    self.name = name
    print("Initialized!")
  def hello(self):
    print("Hello " + self.name + "!")
  def goodbye(self):
    print("Good-bye " + self.name + "!")

In [4]:
m = Man("David")
m.hello()
m.goodbye()

Initialized!
Hello David!
Good-bye David!


1.5.1 넘파이 가져오기

In [5]:
import numpy as np

1.5.2 넘파이 배열 생성하기

In [6]:
x = np.array([1.0, 2.0, 3.0])

In [7]:
print(x)

[1. 2. 3.]


In [8]:
type(x)

numpy.ndarray

1.5.3 넘파이의 산술 연산

In [9]:
x = np.array([1.0, 2.0, 3.0])

In [10]:
y = np.array([2.0, 4.0, 6.0])

In [11]:
x + y

array([3., 6., 9.])

In [12]:
x - y

array([-1., -2., -3.])

In [13]:
x * y

array([ 2.,  8., 18.])

In [14]:
x / y

array([0.5, 0.5, 0.5])

In [15]:
x = np.array([1.0, 2.0, 3.0])

In [16]:
x / 2.0

array([0.5, 1. , 1.5])

1.5.4 넘파이의 N차원 배열

In [17]:
A = np.array([[1, 2], [3, 4]])

In [18]:
print(A)

[[1 2]
 [3 4]]


In [19]:
A.shape

(2, 2)

In [20]:
A.dtype

dtype('int64')

In [21]:
B = np.array([[3, 0],[0, 6]])

In [22]:
A + B

array([[ 4,  2],
       [ 3, 10]])

In [23]:
A * B

array([[ 3,  0],
       [ 0, 24]])

In [24]:
print(A)

[[1 2]
 [3 4]]


In [25]:
A * 10

array([[10, 20],
       [30, 40]])

1.5.5 브로드캐스트

In [26]:
A = np.array([[1,2], [3, 4]])

In [27]:
B = np.array([10, 20])

In [28]:
A * B

array([[10, 40],
       [30, 80]])

1.5.6 원소 접근

In [29]:
X = np.array([[51, 55], [14, 19], [0, 4]])

In [30]:
print(X)

[[51 55]
 [14 19]
 [ 0  4]]


In [31]:
X[0]

array([51, 55])

In [32]:
X[0][1]

55

In [33]:
for row in X:
  print(row)

[51 55]
[14 19]
[0 4]


In [34]:
X = X.flatten() #해결하지 못한 부분 내장 함수 또는 메소드 '개체에'flatten '속성이 없다고 함.

In [35]:
print(X)

[51 55 14 19  0  4]


In [36]:
X[np.array([0, 2, 4])]

array([51, 14,  0])

In [37]:
X > 15

array([ True,  True, False,  True, False, False])

In [38]:
X[X>15]

array([51, 55, 19])