<a href="https://colab.research.google.com/github/Hallymhwangbo/2020-AI_minseo/blob/master/02_4_MathPrimer.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## Math Primer for AI

In [17]:
import numpy as np

## Matrix multiplication

In [18]:
a = np.array([[1, -3, 2], [4, 0, -5]])
print(a)

[[ 1 -3  2]
 [ 4  0 -5]]


In [19]:
a.shape

(2, 3)

In [20]:
b = np.array([[3], [1], [2]])
print(b)

[[3]
 [1]
 [2]]


In [21]:
c = np.matmul(a, b)
print(c)

[[4]
 [2]]


In [22]:
d = np.dot(a, b)
print(d)

[[4]
 [2]]


matmul과 dot의 결과 같다.

In [23]:
c.shape

(2, 1)

In [24]:
d.shape

(2, 1)